import { alpha } from '@/constants/palette'
import { semanticColors } from '@/constants/semantic-colors'
import { radii, spacing } from '@/constants/spacing'

export const profileDesignSpec = {
  colors: {
    background: semanticColors.app.backgroundDeep,
    cardBackground: semanticColors.surface.solidCard,
    primaryText: semanticColors.text.headingOnDark,
    secondaryText: semanticColors.text.neutralMuted,
    inactiveTab: semanticColors.text.eyebrow,
    activeTabUnderline: semanticColors.accent.ctaSolid,
    positiveChange: semanticColors.text.success,
    negativeChange: semanticColors.text.danger,
    tabBorder: semanticColors.border.strong,
    unfollowBackground: alpha.white8,
    unfollowText: semanticColors.text.dimmed,
    avatarGradientStart: '#FACC15',
    avatarGradientEnd: '#E8920D',
  },
  header: {
    bottomPadding: spacing[3],
    horizontalPadding: spacing[4],
    avatarSize: 30,
    avatarGap: spacing[2],
    addressFontSize: 14,
    addressLineHeight: 18,
    addressLetterSpacing: -0.14,
    settingsIconSize: 16,
    settingsTouchSize: 30,
  },
  balance: {
    fontSize: 28,
    lineHeight: 32,
    letterSpacing: -0.84,
    changeFontSize: 13,
    changeLineHeight: 16,
    changeGap: spacing[1],
    periodFontSize: 12,
    periodLineHeight: 16,
    topPadding: spacing[3],
    bottomPadding: spacing[4],
    horizontalPadding: spacing[4],
  },
  allocation: {
    barHeight: 4,
    barRadius: 2,
    gap: 3,
    bottomPadding: spacing[5],
    horizontalPadding: spacing[4],
  },
  tabs: {
    fontSize: 13,
    lineHeight: 16,
    letterSpacing: 0.26,
    paddingVertical: spacing[2.5],
    paddingHorizontal: spacing[4],
    underlineHeight: 2,
    sectionHorizontalPadding: spacing[4],
  },
  card: {
    borderRadius: radii.DEFAULT,
    padding: spacing[4],
    gap: spacing[3],
    listGap: spacing[2],
    listTopPadding: spacing[3],
    listBottomPadding: spacing[6],
    listHorizontalPadding: spacing[4],
    iconSize: 42,
    innerGap: 2,
    nameFontSize: 15,
    nameLineHeight: 18,
    amountFontSize: 13,
    amountLineHeight: 16,
    valueFontSize: 15,
    valueLineHeight: 18,
    changeFontSize: 13,
    changeLineHeight: 16,
  },
  watchlistCard: {
    padding: spacing[3.5],
    unfollowRadius: radii.sm,
    unfollowPaddingVertical: spacing[1.5],
    unfollowPaddingHorizontal: spacing[3],
    unfollowFontSize: 12,
    unfollowLineHeight: 16,
    changeGap: spacing[1],
  },
} as const
