import { alpha } from '@/constants/palette'
import { semanticColors } from '@/constants/semantic-colors'

export const homeDesignSpec = {
  header: {
    horizontalPadding: 24,
    topPadding: 16,
    bottomPadding: 20,
    tabGap: 16,
    selectedTabOpacity: 1,
    mutedTabOpacity: 0.6,
    gradientColors: [alpha.black80, alpha.transparent] as const,
    searchIconSize: 24,
  },
  card: {
    shellTopPadding: 80,
    shellBottomPadding: 0,
    infoHorizontalPadding: 16,
    infoVerticalPadding: 16,
    infoGap: 12,
    ctaHorizontalPadding: 16,
    ctaVerticalPadding: 16,
    ctaGap: 8,
    ctaRadius: 16,
    ctaHeight: 56,
    metricsGap: 16,
    badgeRadius: 12,
    badgeHorizontalPadding: 8,
    badgeVerticalPadding: 4,
    chartTopOffset: 66,
    chartPreferredHeight: 390,
    chartMinHeight: 250,
    avatarSize: 48,
    avatarEdgeInset: 16,
    avatarBottomOffset: 324,
  },
  tabBar: {
    height: 80,
    contentHeight: 60,
    activeOpacity: 1,
    inactiveOpacity: 0.5,
    background: semanticColors.tabBar.feedBackground,
    border: semanticColors.tabBar.feedBorder,
    activeBorder: semanticColors.tabBar.activeIndicator,
    activeGradientTop: semanticColors.tabBar.feedGradientTop,
    activeGradientBottom: semanticColors.tabBar.feedGradientBottom,
  },
} as const
