import { white } from '@/constants/palette'
import { semanticColors } from '@/constants/semantic-colors'
import { iconSize, radii, spacing } from '@/constants/spacing'

export const settingsDesignSpec = {
  colors: {
    background: semanticColors.app.backgroundSettings,
    sectionHeader: semanticColors.accent.badge,
    rowTitle: semanticColors.text.settingsTitle,
    rowSubtitle: semanticColors.text.settingsSubtitle,
    mutedText: semanticColors.text.settingsMuted,
    dangerText: semanticColors.text.dangerSoft,
    divider: semanticColors.border.settingsDivider,
    toggleOn: semanticColors.accent.badge,
    toggleOff: semanticColors.surface.toggleOff,
    toggleKnob: white,
    radioSelected: semanticColors.accent.badge,
    radioBorder: semanticColors.border.radioInactive,
    selectedRowHighlight: semanticColors.accent.backgroundFaint,
    headerTitle: semanticColors.text.settingsTitle,
    headerBackIcon: semanticColors.text.settingsTitle,
    greenDot: semanticColors.text.success,
    externalLinkIcon: semanticColors.text.settingsMuted,
    dialogBackground: semanticColors.border.settingsDivider,
    dialogTitle: semanticColors.text.settingsTitle,
    dialogDescription: semanticColors.text.settingsSubtitle,
    dialogCancelText: semanticColors.accent.badge,
    dialogResetBg: semanticColors.button.dangerSoftBg,
    dialogResetText: semanticColors.button.dangerSoftText,
  },
  header: {
    paddingTop: spacing[4],
    paddingBottom: spacing[4],
    horizontalPadding: spacing[0],
    backButtonSize: spacing[12],
    titleFontSize: 22,
    titleLineHeight: 28,
  },
  section: {
    headerFontSize: 12,
    headerLineHeight: 16,
    headerLetterSpacing: 0.48,
    headerPaddingTop: spacing[4],
    headerPaddingBottom: spacing[2],
    headerPaddingHorizontal: spacing[4],
  },
  row: {
    height: 56,
    dangerHeight: 48,
    paddingLeft: spacing[4],
    paddingRight: spacing[6],
    gap: spacing[4],
    iconSize: iconSize.md,
    titleFontSize: 16,
    titleLineHeight: 24,
    subtitleFontSize: 14,
    subtitleLineHeight: 20,
  },
  toggle: {
    width: 52,
    height: 32,
    borderRadius: 16,
    padding: 2,
    knobSizeOff: 16,
    knobSizeOn: 24,
  },
  radio: {
    size: 20,
    borderWidth: 2,
    borderRadius: 10,
    innerDotSize: 10,
  },
  divider: {
    height: 1,
    marginHorizontal: spacing[4],
    marginBottom: spacing[2],
  },
  dialog: {
    width: 312,
    borderRadius: radii['2xl'],
    padding: spacing[6],
    gap: spacing[4],
    titleFontSize: 24,
    titleLineHeight: 32,
    descriptionFontSize: 14,
    descriptionLineHeight: 20,
    buttonBorderRadius: 20,
    buttonPaddingVertical: spacing[2.5],
    buttonPaddingHorizontal: spacing[6],
    buttonFontSize: 14,
    buttonLineHeight: 18,
    buttonLetterSpacing: 0.14,
  },
  subScreen: {
    descriptionPaddingHorizontal: spacing[4],
    descriptionPaddingVertical: spacing[2],
    descriptionFontSize: 14,
    descriptionLineHeight: 20,
    tokenIconSize: 40,
    rangeNoteFontSize: 12,
    rangeNoteLineHeight: 16,
    rangeNotePaddingHorizontal: spacing[4],
  },
} as const
