import { semanticColors } from '@/constants/semantic-colors'
import { radii, spacing } from '@/constants/spacing'

export const tokenDetailsDesignSpec = {
  colors: {
    background: semanticColors.app.backgroundDeep,
    headerText: semanticColors.text.headingOnDark,
    secondaryText: semanticColors.text.neutralMuted,
    priceText: semanticColors.text.headingOnDark,
    positiveChange: semanticColors.text.success,
    negativeChange: semanticColors.text.danger,
    timeRangeActive: semanticColors.accent.ctaSolid,
    timeRangeActiveText: semanticColors.button.buyText,
    timeRangeInactive: semanticColors.app.backgroundPanelAlt,
    timeRangeInactiveText: semanticColors.text.neutralMuted,
    sectionTitle: semanticColors.text.neutralMuted,
    cardBackground: semanticColors.app.backgroundPanel,
    cardDivider: semanticColors.app.backgroundPanelAlt,
    rowLabel: semanticColors.text.neutralMuted,
    rowValue: semanticColors.text.primary,
    bodyText: semanticColors.text.secondary,
    linkPillBackground: semanticColors.app.backgroundPanelAlt,
    linkPillText: semanticColors.text.secondary,
    linkPillIcon: semanticColors.text.neutralMuted,
    metricLabel: semanticColors.text.neutralMuted,
    metricValue: semanticColors.text.primary,
    statusGreen: semanticColors.text.success,
    activityBuyBg: semanticColors.chart.bullTrail,
    activitySellBg: semanticColors.chart.bearTrail,
    activityBuyIcon: semanticColors.chart.bullBody,
    activitySellIcon: semanticColors.chart.bearBody,
    followBackground: semanticColors.app.backgroundPanelAlt,
    followBorder: semanticColors.border.subtle,
    followText: semanticColors.text.primary,
    ctaBorder: semanticColors.border.subtle,
    buyBackground: semanticColors.button.buyBackground,
    buyText: semanticColors.button.buyText,
    sellBackground: semanticColors.button.sellBackground,
    sellText: semanticColors.button.sellText,
  },
  header: {
    horizontalPadding: spacing[4],
    topPadding: spacing[2],
    bottomPadding: spacing[3],
    navIconSize: 24,
    nameGap: 1,
    nameFontSize: 18,
    nameLineHeight: 22,
    symbolFontSize: 13,
    symbolLineHeight: 16,
    followPaddingVertical: spacing[1.5],
    followPaddingHorizontal: spacing[3.5],
    followFontSize: 13,
    followLineHeight: 16,
  },
  price: {
    horizontalPadding: spacing[4],
    topPadding: spacing[1],
    fontSize: 32,
    lineHeight: 38,
    letterSpacing: -0.64,
    changeFontSize: 14,
    changeLineHeight: 18,
    periodFontSize: 12,
    periodLineHeight: 16,
    changeGap: spacing[2],
  },
  chart: {
    height: 200,
    topPadding: spacing[3],
  },
  timeRange: {
    horizontalPadding: spacing[4],
    topPadding: spacing[2],
    gap: spacing[1],
    pillPaddingVertical: spacing[1.5],
    pillPaddingHorizontal: spacing[3],
    pillRadius: radii.full,
    fontSize: 12,
    lineHeight: 16,
  },
  section: {
    horizontalPadding: spacing[4],
    topPadding: spacing[6],
    titleFontSize: 13,
    titleLineHeight: 16,
    titleLetterSpacing: 0.52,
    titleGap: spacing[2.5],
  },
  position: {
    cardPadding: spacing[3.5],
    cardRadius: radii.md,
    labelFontSize: 12,
    labelLineHeight: 14,
    valueFontSize: 16,
    valueLineHeight: 20,
    valueGap: spacing[0.5],
  },
  infoRow: {
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    cardRadius: radii.md,
    labelFontSize: 14,
    labelLineHeight: 18,
    valueFontSize: 14,
    valueLineHeight: 18,
    mintFontSize: 13,
  },
  about: {
    bodyFontSize: 14,
    bodyLineHeight: 20,
    linkGap: spacing[2],
    linkTopPadding: spacing[1],
    linkPillPaddingVertical: spacing[2],
    linkPillPaddingHorizontal: spacing[3.5],
    linkPillRadius: radii.full,
    linkIconSize: 14,
    linkFontSize: 13,
    linkLineHeight: 16,
    linkIconGap: spacing[1.5],
  },
  performance: {
    gridGap: spacing[3],
    cardPadding: spacing[3.5],
    cardRadius: radii.md,
    labelFontSize: 12,
    labelLineHeight: 14,
    valueFontSize: 16,
    valueLineHeight: 20,
    valueGap: spacing[1],
  },
  security: {
    cardRadius: radii.md,
    rowPaddingVertical: spacing[3],
    rowPaddingHorizontal: spacing[4],
    labelFontSize: 14,
    labelLineHeight: 18,
    valueFontSize: 14,
    valueLineHeight: 18,
    dotSize: 8,
    dotGap: spacing[1.5],
  },
  activity: {
    rowGap: spacing[2],
    rowPadding: spacing[3],
    rowRadius: radii.md,
    iconContainerSize: 36,
    iconSize: 16,
    labelFontSize: 14,
    labelLineHeight: 18,
    dateFontSize: 12,
    dateLineHeight: 14,
    amountFontSize: 14,
    amountLineHeight: 18,
    valueFontSize: 12,
    valueLineHeight: 14,
  },
  cta: {
    horizontalPadding: spacing[4],
    bottomPadding: spacing[8],
    topPadding: spacing[3],
    gap: spacing[3],
    buttonHeight: spacing[14],
    buttonRadius: radii.DEFAULT,
    fontSize: 16,
    lineHeight: 20,
  },
} as const
